apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: ingress-nginx
    name: prometheus-configuration
  namespace: ingress-nginx
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
    scrape_configs:
    - job_name: minio 
      metrics_path: /minio/prometheus/metrics
      static_configs:
      #- targets: ['147.75.83.181:30269']
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: minio #getting pod via label "app=minio"
        action: keep
    - job_name: elasticsearch
      metrics_path: /metrics
      static_configs:
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: k8s-elastic-exporter #getting pod via label "app=k8s-elastic-exporter"
        action: keep