{
 "title": "ElasticSearch-Main",
 "description": "DIsplay ElasticSearch key metrics from Prometheus",
 "tags": [
  "prometheus",
  "elasticsearch"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 1h, 6h, 1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(elasticsearch_cluster_health_status, cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(elasticsearch_process_cpu_percent{cluster=\"$cluster\"}, name)"
   },
   {
    "name": "shard_type",
    "label": "Shard Type",
    "query": "label_values(es_cluster_shards_number, type)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(elasticsearch_cluster_health_status == 0) +1",
     "legendFormat": "GREEN"
    },
    {
     "expr": "(elasticsearch_cluster_health_status == 1) +1",
     "legendFormat": "YELLOW"
    },
    {
     "expr": "(elasticsearch_cluster_health_status == 2) - 1",
     "legendFormat": "RED"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(elasticsearch_indices_docs{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$shard_type shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_shards{cluster=\"$cluster\",type=\"$shard_type\"})"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\",type=\"$shard_type\"})"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_process_cpu_percent{cluster=\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "max(elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\", name=~\"$node\"})",
       "legendFormat": "{$node}"
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "percentunit", "label": "Disk" }
     ],
     "targets": [
      {
       "expr": "1 - elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\",name=~\"$node\"} / elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\",name=~\"$node\"}",
       "legendFormat": "{{name}} - {{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents indexing rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indexing latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$interval]) / rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\", name=~\"$node\"}[$interval]) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Search rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Searches/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Search latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[$interval]) / rate(es_indices_search_query_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents count (with replicas)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_docs{cluster=\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents deleting rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_docs_deleted{cluster=\"$cluster\", name=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents merging rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Merges/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_merges_docs_total{cluster=\"$cluster\",name=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Field data memory size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_fielddata_memory_size_bytes{cluster=\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Field data evictions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_fielddata_evictions{cluster=\"$cluster\", name=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes", "label": "Size" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_query_cache_cache_size{cluster=\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_query_cache_evictions{cluster=\"$cluster\", name=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query cache hits",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Hits/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_query_cache_count{cluster=\"$cluster\", name=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query cache misses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Misses/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_querycache_miss_number{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexing throttling",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_store_throttle_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merging throttling",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_merges_total_throttled_time_seconds{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes", "label": "Heap" }
     ],
     "targets": [
      { "expr": "go_memstats_heap_inuse_bytes" }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "GC/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",name=~\"$node\"}[$interval])",
       "legendFormat": "{{name}} - {{gc}}"
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=\"$cluster\", name=~\"$node\"}[$interval])",
       "legendFormat": "{{name}} - {{gc}}"
      }
     ]
    }
   ]
  }
 ]
}