{
 "title": "MinIO Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(minio_total_disks,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Disks",
   "type": "singlestat",
   "description": "Total disks of current Minio server instance",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "minio_total_disks{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Offline Disks",
   "type": "singlestat",
   "description": "Offline disks of current Minio server instance",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "minio_offline_disks{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Start time of the Minio server instance",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{instance=\"$instance\" ,job=\"minio\"})",
     "legendFormat": "Start time of the Minio server"
    }
   ]
  },
  {
   "title": "Data Transmited",
   "type": "graph",
   "description": "Data sent by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_sent_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "graph",
   "description": "Data received by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_received_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Received:"
    }
   ]
  },
  {
   "title": "Total In/Out Throughput",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_received_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Received: "
    },
    {
     "expr": "rate(minio_network_sent_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "HTTP Requests duration/s",
   "type": "graph",
   "description": "The current aggregate time spent servicing all HTTP requests  in seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"GET\",instance=\"$instance\"}[5m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"POST\",instance=\"$instance\"}[5m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"PUT\",instance=\"$instance\"}[5m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"HEAD\",instance=\"$instance\"}[5m])",
     "legendFormat": "HEAD"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"DELETE\",instance=\"$instance\"}[5m])",
     "legendFormat": "DELETE"
    }
   ]
  }
 ]
}